
# To compile this project, multiple clang flags are required.

CC := clang # Only clang builds it.

ADDITIONAL_OBJCFLAGS := -Wall -ObjC -Xclang -fobjc-arc -fobjc-default-synthesized-properties -fblocks
ADDITIONAL_CFLAGS := -finline-functions
ADDITIONAL_INCLUDE_DIRS := -I..
