
before-all::
	printf "{ \"git-version\" = \"%s\"; }\n" `git describe --always --tag` > git-version.plist

after-all::
	-ln -sf FusionKit.framework/Headers FusionKit
	-ln -sf FusionKit.framework/libFusionKit.so libFusionKit.so

before-clean::
	-rm FusionKit
	-rm libFusionKit.so

after-clean::
	-rm git-version.plist
	
