
before-all::
	@echo " Generating version file..."
	@printf "{ \"git-version\" = \"%s\"; }\n" `git describe --always --tag` > git-version.plist

after-all::
	@echo " Generating dependency symlinks..."
	@-ln -sf FusionKit.framework/Headers FusionKit
	@-ln -sf FusionKit.framework/libFusionKit.so libFusionKit.so

before-clean::
	@echo " Removing dependency symlinks..."
	@-rm FusionKit
	@-rm libFusionKit.so

after-clean::
	@echo " Removing version file..."
	@-rm git-version.plist
	
