
before-all::
	printf "{ \"git-version\" = \"%s\"; }\n" `git describe --always --tag` > git-version.plist

after-all::
	ln FusionProtocol.framework/Headers FusionProtocol
	ln FusionProtocol.framework/libFusionProtocol.so libFusionProtocol.so

before-clean::
	-rm FusionProtocol
	-rm libFusionProtocol.so

after-clean::
	-rm git-version.plist
